const BRANCHES=["บางบัวทอง","หลังสวน","ตรัง"], CATEGORIES=["หมูบด A","หมูบด B","หมูบด 5","หมูบดผสมไก่","หมูอ้วนหมูบด(หมูบด6)","ขาหน้าล้วน","ขาหลังล้วน","ขาหลังเลาะ","คากิ","คาตั้งกลม","เครื่องในต้ม","หมูรวมต้ม","ไก่บดA","ไก่สับ","ไก่รวมต้ม","น่องไก่","สะโพกไก่"];
const state={branch:"",category:"",items:[]}; const $=x=>document.getElementById(x);
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
function choices(){ $("branches").innerHTML=BRANCHES.map(x=>`<button class="choice ${state.branch===x?'active':''}" data-branch="${x}">${x}</button>`).join(""); $("categories").innerHTML=CATEGORIES.map(x=>`<button class="choice ${state.category===x?'active':''}" data-cat="${x}">${x}</button>`).join(""); document.querySelectorAll("[data-branch]").forEach(b=>b.onclick=()=>{state.branch=b.dataset.branch;choices()});document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;choices()}) }
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});const j=await r.json();if(!r.ok)throw Error(j.message||"เกิดข้อผิดพลาด");return j}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){if(!state.items.length)$("items").innerHTML='<div class="empty">ยังไม่มีรูปฉลาก</div>';else $("items").innerHTML=state.items.map((x,i)=>`<div class="item"><img src="${x.image}" alt="ฉลาก"><div><label>ชื่อสินค้า</label><input data-i="${i}" data-k="name" value="${esc(x.name)}" placeholder="ชื่อสินค้า"><div class="message ${x.loading?'loading':x.valid?'good':'bad'}">${esc(x.message)}</div></div><div class="weight"><label>น้ำหนักสุทธิ (กก.)</label><input type="number" min="0.001" step="0.001" data-i="${i}" data-k="weight" value="${x.weight??''}" placeholder="0.000"></div><div class="remove"><button class="danger" data-del="${i}">ลบ</button></div></div>`).join("");document.querySelectorAll("[data-k]").forEach(e=>e.oninput=()=>{const x=state.items[+e.dataset.i];x[e.dataset.k]=e.value;x.valid=!!x.name&&Number(x.weight)>0;x.message=x.valid?"ตรวจสอบแล้ว พร้อมรวมยอด":"ภาพไม่ชัด กรุณาถ่ายรูปใหม่หรืออัปโหลดรูปใหม่";renderSummary()});document.querySelectorAll("[data-del]").forEach(e=>e.onclick=()=>{state.items.splice(+e.dataset.del,1);render();renderSummary()});renderSummary()}
function renderSummary(){const sums={};state.items.filter(x=>x.valid).forEach(x=>sums[x.name]=(sums[x.name]||0)+Number(x.weight));const rows=Object.entries(sums);$("summary").innerHTML=rows.length?rows.map(([n,w])=>`<div class="sumrow"><span>${esc(state.category||'-')} — ${esc(n)}</span><span>${w.toFixed(3)} กก.</span></div>`).join(""):'<div class="empty">ยังไม่มีรายการที่พร้อมรวมยอด</div>'}
function readFile(file){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}
async function addFiles(files){if(!state.branch||!state.category){$("notice").innerHTML='<div class="alert">กรุณาเลือกสาขาและหมวดแปรรูปก่อนอัปโหลดรูป</div>';return}$("notice").innerHTML="";for(const file of files){if(!file.type.startsWith("image/"))continue;const image=await readFile(file),item={image,name:"",weight:"",valid:false,loading:true,message:"AI กำลังอ่านฉลาก…"};state.items.push(item);render();try{const x=await api("/api/read-label",{method:"POST",body:JSON.stringify({image})});Object.assign(item,{name:x.name||"",weight:x.weight??"",valid:!!x.ok,loading:false,message:x.message})}catch(e){Object.assign(item,{loading:false,message:e.message})}render()}}
let allHistory=false;
async function report(){const q=new URLSearchParams({branch:$("reportBranch").value,category:$("reportCategory").value});if(allHistory)q.set("all","1");else{q.set("date_from",$("reportDateFrom").value);q.set("date_to",$("reportDateTo").value)}try{const rows=await api("/api/report?"+q);let total=0;$("report").innerHTML=rows.length?rows.map(x=>{total+=x.weight_kg;return `<div class="reportrow"><span><span class="report-date">${esc(x.tx_date)}</span>${esc(x.branch)} · ${esc(x.category)} · ${esc(x.product_name)} <small>(${x.images} รูป)</small></span><span>${Number(x.weight_kg).toFixed(3)} กก.</span></div>`}).join("")+`<div class="reportrow total"><span>น้ำหนักรวมทั้งหมด</span><span>${total.toFixed(3)} กก.</span></div>`:'<div class="empty">ยังไม่มีข้อมูลในช่วงวันที่เลือก</div>'}catch(e){$("report").textContent=e.message}}
async function init(){choices();$("date").value=$("reportDateFrom").value=$("reportDateTo").value=today();$("date").min=$("date").max=today();$("reportBranch").innerHTML+=""+BRANCHES.map(x=>`<option>${x}</option>`).join("");$("reportCategory").innerHTML+=""+CATEGORIES.map(x=>`<option>${x}</option>`).join("");const s=await api("/api/status");$("aiStatus").textContent=s.ai?"AI พร้อมอ่านฉลาก":"โหมดตรวจแก้ด้วยมือ";if(s.ai)$("aiStatus").classList.add("ok");report()}
$("pick").onclick=()=>$("files").click();$("files").onchange=e=>{addFiles([...e.target.files]);e.target.value=""};$("clear").onclick=()=>{if(confirm("ล้างรูปทั้งหมดในชุดนี้หรือไม่?")){state.items=[];render();renderSummary()}};$("save").onclick=async()=>{if(!state.branch||!state.category)return alert("กรุณาเลือกสาขาและหมวดแปรรูป");const valid=state.items.filter(x=>x.valid);if(!valid.length)return alert("ไม่มีรายการที่ผ่านการตรวจสอบ");try{const x=await api("/api/records",{method:"POST",body:JSON.stringify({date:$("date").value,branch:state.branch,category:state.category,items:valid})});alert(`บันทึกสำเร็จ ${x.saved} รายการ`);state.items=[];render();report()}catch(e){alert(e.message)}};["reportDateFrom","reportDateTo"].forEach(x=>$(x).onchange=()=>{allHistory=false;report()});["reportBranch","reportCategory"].forEach(x=>$(x).onchange=report);$("showAllHistory").onclick=()=>{allHistory=true;report()};$("showToday").onclick=()=>{allHistory=false;$("reportDateFrom").value=$("reportDateTo").value=today();report()};init();
