const ORDER_PRODUCTS=[];
const state={quantities:{}},$=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const items=()=>ORDER_PRODUCTS.map(product_name=>({product_name,quantity:Number(state.quantities[product_name]||0),unit:"กก."})).filter(x=>x.quantity>0);
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt}),j=await r.json();if(!r.ok)throw Error(j.message||"เกิดข้อผิดพลาด");return j}
function summary(){const rows=items(),total=rows.reduce((s,x)=>s+x.quantity,0);$("summaryBranch").textContent=$("orderBranch").value||"กรุณาเลือกสาขา";$("orderSummary").innerHTML=rows.length?rows.map(x=>`<div class="summary-order-row"><span>${esc(x.product_name)}</span><strong>${x.quantity.toFixed(2)} ${x.unit}</strong></div>`).join(""):'<div class="empty">ยังไม่มีรายการ</div>';$("totalWeight").textContent=total.toFixed(2)}
function render(){const q=$("orderSearch").value.trim().toLowerCase(),products=ORDER_PRODUCTS.filter(x=>x.toLowerCase().includes(q));$("orderRows").innerHTML=products.map((name,i)=>`<tr class="${Number(state.quantities[name])>0?'selected':''}"><td>${i+1}</td><td>${esc(name)}</td><td><input data-product="${esc(name)}" type="number" min="0" step="0.01" inputmode="decimal" value="${esc(state.quantities[name]??'')}" placeholder="0.00"></td><td>กก.</td></tr>`).join("")||'<tr><td colspan="4" class="empty">ไม่พบรายการสินค้า</td></tr>';document.querySelectorAll('[data-product]').forEach(input=>input.oninput=()=>{if(input.value!==''&&Number(input.value)<0)input.value='0';state.quantities[input.dataset.product]=input.value;input.closest('tr').classList.toggle('selected',Number(input.value)>0);summary()})}
function reset(){state.quantities={};$("orderNote").value="";$("orderNotice").innerHTML="";render();summary()}
$("orderSearch").oninput=render;$("clearOrderSearch").onclick=()=>{$("orderSearch").value="";render()};$("orderBranch").onchange=summary;$("clearOrder").onclick=()=>{if(confirm("ล้างข้อมูลคำสั่งซื้อทั้งหมดหรือไม่?"))reset()};
$("saveOrder").onclick=async()=>{const branch=$("orderBranch").value,rows=items(),total=rows.reduce((s,x)=>s+x.quantity,0);if(!branch)return alert("กรุณาเลือกสาขา");if(!rows.length)return alert("กรุณากรอกสินค้าอย่างน้อย 1 รายการที่มีน้ำหนักมากกว่า 0");if(!confirm(`ยืนยันบันทึกคำสั่งซื้อของสาขา ${branch} น้ำหนักรวม ${total.toFixed(2)} กก. หรือไม่?`))return;try{await api('/api/orders',{method:'POST',body:JSON.stringify({branch,note:$("orderNote").value,items:rows})});reset();$("orderNotice").innerHTML='<div class="save-success">บันทึกคำสั่งซื้อเรียบร้อยแล้ว</div>'}catch(e){$("orderNotice").innerHTML=`<div class="alert">${esc(e.message)}</div>`}};
window.authReady.then(async user=>{const catalog=await api('/api/product-catalog');ORDER_PRODUCTS.push(...catalog.pork);$("orderDate").textContent=new Intl.DateTimeFormat("th-TH",{dateStyle:"long"}).format(new Date());$("orderedBy").textContent=user.username;if(user.role==='manager'){$("orderBranch").value=user.branch;$("orderBranch").disabled=true}render();summary()});
