const ORDER_PRODUCTS=["เนื้อแดง","สะโพก","สามชั้น","สามชั้นบาง","สามชั้นลอกหนัง","ซี่โครง","ซี่โครงอ่อน","ซี่โครงแข็ง","กระดูกอ่อน","เอียวเล้ง","ขาหน้า","ขาหลัง","สันนอก","สันใน","สันคอ","หมูบด","หนังหมู","มันหมู","ไส้หมู","ไส้อ่อน","ไส้ใหญ่","ตับ","หัวใจ","ไต","ม้าม","ปอด","กระเพาะหมู","เซี่ยงจี้","หัวหมู","หูหมู","แก้มหมู","ลิ้นหมู","หางหมู","คากิ"];
const orderState={quantities:{}};const byId=id=>document.getElementById(id);const escapeText=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function localDate(){return new Intl.DateTimeFormat("th-TH",{dateStyle:"long"}).format(new Date())}
async function orderApi(url,options={}){const response=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const result=await response.json();if(!response.ok)throw Error(result.message||"เกิดข้อผิดพลาด");return result}
function currentItems(){return ORDER_PRODUCTS.map(product_name=>({product_name,quantity:Number(orderState.quantities[product_name]||0),unit:"กก."})).filter(item=>item.quantity>0)}
function renderOrder(){byId("orderRows").innerHTML=ORDER_PRODUCTS.map((name,index)=>{const value=orderState.quantities[name]??"";return `<tr class="${Number(value)>0?"selected":""}"><td>${index+1}</td><td>${escapeText(name)}</td><td><input aria-label="น้ำหนัก ${escapeText(name)}" data-product="${escapeText(name)}" type="number" min="0" step="0.01" inputmode="decimal" value="${escapeText(value)}" placeholder="0.00"></td><td>กก.</td></tr>`}).join("");document.querySelectorAll("[data-product]").forEach(input=>input.oninput=()=>{if(input.value!==""&&Number(input.value)<0)input.value="0";orderState.quantities[input.dataset.product]=input.value;input.closest("tr").classList.toggle("selected",Number(input.value)>0);renderOrderSummary()})}
function renderOrderSummary(){const items=currentItems(),total=items.reduce((sum,item)=>sum+item.quantity,0);byId("summaryBranch").textContent=byId("orderBranch").value||"กรุณาเลือกสาขา";byId("orderSummary").innerHTML=items.length?items.map(item=>`<div class="summary-order-row"><span>${escapeText(item.product_name)}</span><strong>${item.quantity.toFixed(2)} กก.</strong></div>`).join(""):'<div class="empty">ยังไม่มีรายการ</div>';byId("totalWeight").textContent=total.toFixed(2)}
function resetOrder(){orderState.quantities={};byId("orderNote").value="";byId("orderNotice").innerHTML="";renderOrder();renderOrderSummary()}
async function initOrder(){const user=await window.authReady;byId("orderDate").textContent=localDate();byId("orderedBy").textContent=user.username;if(user.role==="manager"){byId("orderBranch").value=user.branch;byId("orderBranch").disabled=true}renderOrder();renderOrderSummary()}
byId("orderBranch").onchange=renderOrderSummary;byId("clearOrder").onclick=()=>{if(confirm("ล้างข้อมูลคำสั่งซื้อทั้งหมดหรือไม่?"))resetOrder()};byId("saveOrder").onclick=async()=>{const branch=byId("orderBranch").value,items=currentItems(),total=items.reduce((sum,item)=>sum+item.quantity,0);if(!branch)return alert("กรุณาเลือกสาขา");if(!items.length)return alert("กรุณากรอกสินค้าอย่างน้อย 1 รายการที่มีน้ำหนักมากกว่า 0");if(!confirm(`ยืนยันบันทึกคำสั่งซื้อของสาขา ${branch} น้ำหนักรวม ${total.toFixed(2)} กก. หรือไม่?`))return;try{await orderApi("/api/orders",{method:"POST",body:JSON.stringify({branch,note:byId("orderNote").value,items})});resetOrder();byId("orderNotice").innerHTML='<div class="save-success">บันทึกคำสั่งซื้อเรียบร้อยแล้ว</div>'}catch(error){byId("orderNotice").innerHTML=`<div class="alert">${escapeText(error.message)}</div>`}};initOrder();
