const ORDER_CATALOG={หมู:[],ไก่:[]};
const state={category:'หมู',quantities:{},pendingRequestId:null,pendingSignature:null},$=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const itemKey=(category,name)=>`${category}\u0000${name}`,items=()=>Object.entries(ORDER_CATALOG).flatMap(([product_category,names])=>names.map(product_name=>({product_category,product_name,quantity:Number(state.quantities[itemKey(product_category,product_name)]||0),unit:'กก.'}))).filter(item=>item.quantity>0);
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt}),text=await r.text();let data={};if(text)try{data=JSON.parse(text)}catch{throw Error('เซิร์ฟเวอร์ส่งข้อมูลไม่ถูกต้อง')}if(!r.ok)throw Error(data.message||'ดำเนินการไม่สำเร็จ');return data}
function summary(){const rows=items(),total=rows.reduce((sum,item)=>sum+item.quantity,0);$("summaryBranch").textContent=$("orderBranch").value||"กรุณาเลือกสาขา";$("orderSummary").innerHTML=rows.length?rows.map(item=>`<div class="summary-order-row"><span>${esc(item.product_category)} · ${esc(item.product_name)}</span><strong>${item.quantity.toFixed(2)} กก.</strong></div>`).join(''):'<div class="empty">ยังไม่มีรายการ</div>';$("totalWeight").textContent=total.toFixed(2)}
function render(){const query=$("orderSearch").value.trim().toLowerCase(),products=ORDER_CATALOG[state.category].filter(name=>name.toLowerCase().includes(query));$("orderCategoryTitle").textContent=`รายการ${state.category}`;$("orderSearch").placeholder=`ค้นหารายการ${state.category}...`;$("orderRows").innerHTML=products.map((name,index)=>{const key=itemKey(state.category,name);return `<tr class="${Number(state.quantities[key])>0?'selected':''}"><td>${index+1}</td><td>${esc(name)}</td><td><input data-product="${esc(name)}" data-category="${state.category}" type="number" min="0" step="0.01" value="${esc(state.quantities[key]??'')}"></td><td>กก.</td></tr>`}).join('');document.querySelectorAll('[data-product]').forEach(input=>input.oninput=()=>{state.quantities[itemKey(input.dataset.category,input.dataset.product)]=input.value;summary();renderSelected(input)})}
function renderSelected(input){input.closest('tr').classList.toggle('selected',Number(input.value)>0)}function selectCategory(category){state.category=category;$("orderSearch").value='';document.querySelectorAll('[data-order-category]').forEach(button=>button.classList.toggle('active',button.dataset.orderCategory===category));render()}function reset(){state.quantities={};$("orderNote").value='';render();summary()}
document.querySelectorAll('[data-order-category]').forEach(button=>button.onclick=()=>selectCategory(button.dataset.orderCategory));$("orderSearch").oninput=render;$("clearOrderSearch").onclick=()=>{$("orderSearch").value='';render()};$("clearOrder").onclick=reset;$("orderBranch").onchange=summary;
$("saveOrder").onclick=async()=>{const rows=items(),branch=$("orderBranch").value;if(!branch)return alert('กรุณาเลือกสาขา');if(!rows.length)return alert('กรุณากรอกสินค้า');const signature=JSON.stringify({branch,items:rows,note:$("orderNote").value});if(state.pendingSignature!==signature){state.pendingSignature=signature;state.pendingRequestId=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}try{const result=await api('/api/orders',{method:'POST',body:JSON.stringify({request_id:state.pendingRequestId,branch,note:$("orderNote").value,items:rows})});state.pendingRequestId=null;state.pendingSignature=null;reset();$("orderNotice").innerHTML=`<div class="save-success">บันทึกสำเร็จ Order ID: ${result.order_id}</div>`}catch(error){$("orderNotice").innerHTML=`<div class="alert">${esc(error.message)}</div>`}};
window.authReady.then(async user=>{const catalog=await api('/api/product-catalog');ORDER_CATALOG.หมู.push(...catalog.pork);ORDER_CATALOG.ไก่.push(...catalog.chicken);$("orderDate").textContent=new Intl.DateTimeFormat('th-TH',{dateStyle:'long'}).format(new Date());$("orderedBy").textContent=user.username;if(user.role==='manager'){$("orderBranch").value=user.branch;$("orderBranch").disabled=true}selectCategory('หมู');summary()});
