const PRODUCTS=["เนื้อแดง","สะโพก","สามชั้น","ซี่โครง","ขาหน้า","ขาหลัง","สันนอก","อกไก่","น่องสะโพก"],BRANCHES=["บางบัวทอง","ตรัง","หลังสวน"];
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,"0"),dateText=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const money=n=>Number.isFinite(n)?Number(n).toFixed(2):"—";let currentRows=[];
async function api(url){const response=await fetch(url);const data=await response.json();if(!response.ok)throw Error(data.message||"เกิดข้อผิดพลาด");return data}
function selectedDate(){const d=new Date();if($("datePreset").value==="yesterday")d.setDate(d.getDate()-1);return $("datePreset").value==="custom"?$("overviewDate").value:dateText(d)}
function analyze(row){const competitors=[row.competitor_1,row.competitor_2,row.competitor_3].map(Number).filter(Number.isFinite),our=row.our_price===null?null:Number(row.our_price),best=competitors.length?Math.min(...competitors):null,diff=our===null||best===null?null:our-best;let status="ยังไม่มีข้อมูล";if(diff<0)status="เราถูกกว่า";else if(diff>0)status="เราแพงกว่า";else if(diff===0)status="ราคาเท่ากัน";return {...row,our,best,diff,status,recorded:[row.our_price,row.competitor_1,row.competitor_2,row.competitor_3].some(v=>v!==null)}}
async function loadOverview(){const branch=$("overviewBranch").value,date=selectedDate();if(!date)return;try{const saved=await api("/api/price-summary?"+new URLSearchParams({date,branch})),map=new Map(saved.map(row=>[`${row.branch}|${row.product_name}`,row])),branches=branch==="ALL"?BRANCHES:[branch];currentRows=branches.flatMap(b=>PRODUCTS.map(product=>analyze(map.get(`${b}|${product}`)||{branch:b,product_name:product,our_price:null,competitor_1:null,competitor_2:null,competitor_3:null})));render()}catch(error){$("overviewRows").innerHTML=`<tr><td colspan="7" class="alert">${error.message}</td></tr>`}}
function render(){const high=currentRows.filter(r=>r.diff>0),low=currentRows.filter(r=>r.diff<0);$("totalItems").textContent=currentRows.length;$("recordedItems").textContent=currentRows.filter(r=>r.recorded).length;$("higherItems").textContent=high.length;$("lowerItems").textContent=low.length;$("overviewRows").innerHTML=currentRows.map((r,i)=>`<tr><th>${r.product_name}</th><td>${r.branch}</td><td>${money(r.our)}</td><td>${money(r.best)}</td><td class="${r.diff>0?'price-high':r.diff<0?'price-low':''}">${r.diff===null?'—':`${r.diff>0?'+':''}${r.diff.toFixed(2)}`}</td><td><span class="overview-status ${r.diff>0?'bad':r.diff<0?'good':'neutral'}">${r.status}</span></td><td><div class="row-actions"><button data-detail="${i}" class="secondary compact">ดูรายละเอียด</button><button data-history="${i}" class="secondary compact">ดูประวัติราคา</button></div></td></tr>`).join("");const review=[...high].sort((a,b)=>b.diff-a.diff);$("reviewItems").innerHTML=review.length?review.map(r=>`<div class="review-row"><span><strong>${r.product_name}</strong><small>${r.branch}</small></span><span class="price-high">แพงกว่า ${r.diff.toFixed(2)} บาท</span></div>`).join(""):'<div class="empty">ไม่มีรายการที่ต้องตรวจสอบ</div>';document.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>showDetail(currentRows[+b.dataset.detail]));document.querySelectorAll("[data-history]").forEach(b=>b.onclick=()=>showHistory(currentRows[+b.dataset.history]))}
function openPanel(title,html){$("detailTitle").textContent=title;$("detailContent").innerHTML=html;$("detailPanel").hidden=false;$("detailPanel").scrollIntoView({behavior:"smooth"})}
function showDetail(r){openPanel(`รายละเอียด ${r.product_name} — ${r.branch}`,`<div class="detail-grid"><div><span>ราคาของเรา</span><strong>${money(r.our_price)}</strong></div><div><span>คู่แข่งเจ้า 1</span><strong>${money(r.competitor_1)}</strong></div><div><span>คู่แข่งเจ้า 2</span><strong>${money(r.competitor_2)}</strong></div><div><span>คู่แข่งเจ้า 3</span><strong>${money(r.competitor_3)}</strong></div></div>`)}
async function showHistory(r){openPanel(`ประวัติราคา ${r.product_name} — ${r.branch}`,'<div class="empty">กำลังโหลด…</div>');try{const rows=await api("/api/price-history?"+new URLSearchParams({branch:r.branch,product:r.product_name}));$("detailContent").innerHTML=rows.length?`<div class="table-wrap"><table class="price-table history-table"><thead><tr><th>วันที่</th><th>ราคาของเรา</th><th>คู่แข่ง 1</th><th>คู่แข่ง 2</th><th>คู่แข่ง 3</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.price_date}</td><td>${money(x.our_price)}</td><td>${money(x.competitor_1)}</td><td>${money(x.competitor_2)}</td><td>${money(x.competitor_3)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">ยังไม่มีประวัติราคา</div>'}catch(error){$("detailContent").innerHTML=`<div class="alert">${error.message}</div>`}}
$("overviewDate").value=dateText(new Date());$("overviewBranch").onchange=loadOverview;$("datePreset").onchange=()=>{$("customDateWrap").hidden=$("datePreset").value!=="custom";loadOverview()};$("overviewDate").onchange=loadOverview;$("closeDetail").onclick=()=>$("detailPanel").hidden=true;loadOverview();
