const receive=id=>document.getElementById(id),receiveEsc=value=>String(value??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let receivingCatalog={หมู:[],ไก่:[]},activeCategory='หมู',draftItems=[],editIndex=-1,receivingRequest=null;
async function receivingApi(url,opt={}){const response=await fetch(url,{headers:{"Content-Type":"application/json"},...opt}),text=await response.text();let data={};if(text)try{data=JSON.parse(text)}catch{throw Error("เซิร์ฟเวอร์ส่งข้อมูลไม่ถูกต้อง")}if(!response.ok)throw Error(data.message||"ดำเนินการไม่สำเร็จ");return data}
function filteredProducts(){const query=receive('receiptSearch').value.trim().toLowerCase();return receivingCatalog[activeCategory].filter(name=>name.toLowerCase().includes(query))}
function renderProductOptions(selected=''){const products=filteredProducts();receive('receiptProduct').innerHTML='<option value="">เลือกสินค้า</option>'+products.map(name=>`<option ${name===selected?'selected':''}>${receiveEsc(name)}</option>`).join('')}
function selectCategory(category){activeCategory=category;document.querySelectorAll('[data-category]').forEach(button=>button.classList.toggle('active',button.dataset.category===category));receive('receiptSearch').value='';renderProductOptions()}
function clearEntry(){editIndex=-1;receive('receiptProduct').value='';receive('entryWeight').value='';receive('entryBags').value='';receive('addReceiptItem').textContent='เพิ่มรายการ'}
function addOrUpdateItem(){const product_name=receive('receiptProduct').value,weight_kg=Number(receive('entryWeight').value),bag_count=Number(receive('entryBags').value||0);if(!product_name)return alert('กรุณาเลือกสินค้า');if(!Number.isFinite(weight_kg)||weight_kg<=0)return alert('น้ำหนักต้องมากกว่า 0');if(!Number.isInteger(bag_count)||bag_count<0)return alert('จำนวนถุงต้องเป็นจำนวนเต็ม 0 หรือมากกว่า');const item={product_category:activeCategory,product_name,weight_kg,bag_count,note:''};if(editIndex>=0)draftItems[editIndex]=item;else draftItems.push(item);receivingRequest=null;clearEntry();renderDraft()}
function editItem(index){const item=draftItems[index];editIndex=index;selectCategory(item.product_category);renderProductOptions(item.product_name);receive('receiptProduct').value=item.product_name;receive('entryWeight').value=item.weight_kg;receive('entryBags').value=item.bag_count;receive('addReceiptItem').textContent='บันทึกการแก้ไข';receive('entryWeight').focus()}
function removeItem(index){draftItems.splice(index,1);receivingRequest=null;if(editIndex===index)clearEntry();renderDraft()}
function categoryTotals(category){const rows=draftItems.filter(item=>item.product_category===category);return {count:rows.length,weight:rows.reduce((sum,item)=>sum+item.weight_kg,0),bags:rows.reduce((sum,item)=>sum+item.bag_count,0)}}
function renderDraft(){receive('receiptRows').innerHTML=draftItems.length?draftItems.map((item,index)=>`<tr><td>${index+1}</td><td>${item.product_category}</td><td>${receiveEsc(item.product_name)}</td><td>${item.weight_kg.toFixed(2)}</td><td>${item.bag_count}</td><td><button class="secondary edit-item" data-index="${index}">แก้ไข</button></td><td><button class="danger remove-item" data-index="${index}">ลบ</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">ยังไม่มีรายการ</td></tr>';document.querySelectorAll('.edit-item').forEach(button=>button.onclick=()=>editItem(Number(button.dataset.index)));document.querySelectorAll('.remove-item').forEach(button=>button.onclick=()=>removeItem(Number(button.dataset.index)));const pork=categoryTotals('หมู'),chicken=categoryTotals('ไก่');receive('receiptItemCount').textContent=draftItems.length;receive('receiptWeightTotal').textContent=(pork.weight+chicken.weight).toFixed(2);receive('receiptBagTotal').textContent=pork.bags+chicken.bags;receive('porkSummary').textContent=`${pork.count} รายการ · ${pork.weight.toFixed(2)} กก. · ${pork.bags} ถุง`;receive('chickenSummary').textContent=`${chicken.count} รายการ · ${chicken.weight.toFixed(2)} กก. · ${chicken.bags} ถุง`}
function clearReceipt(){draftItems=[];editIndex=-1;receivingRequest=null;receive('supplier').value='';receive('purchaseOrder').value='';receive('receiptNote').value='';clearEntry();renderDraft()}
document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>selectCategory(button.dataset.category));receive('receiptSearch').oninput=()=>renderProductOptions();receive('addReceiptItem').onclick=addOrUpdateItem;receive('entryWeight').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();receive('entryBags').focus()}};receive('entryBags').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();addOrUpdateItem();receive('receiptSearch').focus()}};receive('clearReceipt').onclick=()=>{if(confirm('ล้างข้อมูลใบรับสินค้าทั้งหมดหรือไม่?'))clearReceipt()};
receive('saveReceipt').onclick=async()=>{if(!draftItems.length)return alert('กรุณาเพิ่มรายการสินค้า');const payload={received_date:receive('receivingDate').value,branch:receive('receivingBranch').value,supplier:receive('supplier').value,purchase_order_number:receive('purchaseOrder').value,received_by:receive('receivedBy').value,note:receive('receiptNote').value,items:draftItems};const signature=JSON.stringify(payload);if(!receivingRequest||receivingRequest.signature!==signature)receivingRequest={signature,id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`};payload.request_id=receivingRequest.id;const button=receive('saveReceipt');button.disabled=true;try{const result=await receivingApi('/api/receipts',{method:'POST',body:JSON.stringify(payload)});receivingRequest=null;clearReceipt();receive('receivingNotice').innerHTML=`<div class="save-success">บันทึกรับสินค้าเรียบร้อย · ${receiveEsc(result.receipt_number)}</div>`}catch(error){receive('receivingNotice').innerHTML=`<div class="alert">${receiveEsc(error.message)}</div>`}finally{button.disabled=false}};
window.authReady.then(async user=>{const catalog=await receivingApi('/api/product-catalog');receivingCatalog={หมู:catalog.pork,ไก่:catalog.chicken};const today=new Date().toISOString().slice(0,10);receive('receivingDate').value=today;receive('receivingDateText').textContent=new Intl.DateTimeFormat('th-TH',{dateStyle:'long'}).format(new Date());receive('receivingUser').textContent=`${user.username} · ${user.role}`;receive('receivedBy').value=user.username;if(user.role==='manager'){receive('receivingBranch').value=user.branch;receive('receivingBranch').disabled=true}selectCategory('หมู');renderDraft()});
window.getReportExportData=()=>{const now=new Date(),date=receive('receivingDate').value,branch=receive('receivingBranch').value,user=window.currentUser?.username||'';return {title:'รับสินค้าเข้า',filename:`receiving-${date}.xlsx`,metadata:[['วันที่',date],['สาขา',branch]],rows:[['วันที่','เวลา','สาขา','หมวด','สินค้า','น้ำหนัก (กก.)','จำนวนถุง','ผู้บันทึก'],...draftItems.map(item=>[date,now.toLocaleTimeString('th-TH'),branch,item.product_category,item.product_name,item.weight_kg,item.bag_count,user]),['รวม','','','','',draftItems.reduce((sum,item)=>sum+item.weight_kg,0),draftItems.reduce((sum,item)=>sum+item.bag_count,0),'']]}};
